// Generated by: supabase gen types typescript --project-id <your-project-id>
// Run this after applying migrations to regenerate accurate types.
// NOTE: Re-run after every migration to keep types in sync with the schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      championships: {
        Row: {
          id: string;
          name: string;
          season: string;
          status: "not_started" | "active" | "ended";
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          season: string;
          status?: "not_started" | "active" | "ended";
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          season?: string;
          status?: "not_started" | "active" | "ended";
          created_at?: string;
        };
        Relationships: [];
      };
      phases: {
        Row: {
          id: string;
          championship_id: string;
          name: string;
          status: "closed" | "open" | "betting_locked" | "finished";
          pix_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          championship_id: string;
          name: string;
          status?: "closed" | "open" | "betting_locked" | "finished";
          pix_amount: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          championship_id?: string;
          name?: string;
          status?: "closed" | "open" | "betting_locked" | "finished";
          pix_amount?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      matches: {
        Row: {
          id: string;
          phase_id: string;
          home_team: string;
          away_team: string;
          kickoff_at: string;
          home_goals_final: number | null;
          away_goals_final: number | null;
          status: "scheduled" | "finished" | "cancelled" | "postponed";
          external_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          phase_id: string;
          home_team: string;
          away_team: string;
          kickoff_at: string;
          home_goals_final?: number | null;
          away_goals_final?: number | null;
          status?: "scheduled" | "finished" | "cancelled" | "postponed";
          external_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          phase_id?: string;
          home_team?: string;
          away_team?: string;
          kickoff_at?: string;
          home_goals_final?: number | null;
          away_goals_final?: number | null;
          status?: "scheduled" | "finished" | "cancelled" | "postponed";
          external_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      bets: {
        Row: {
          id: string;
          user_id: string;
          match_id: string;
          home_goals_predicted: number;
          away_goals_predicted: number;
          status: "pending" | "confirmed" | "scored";
          points: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          match_id: string;
          home_goals_predicted: number;
          away_goals_predicted: number;
          status?: "pending" | "confirmed" | "scored";
          points?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          match_id?: string;
          home_goals_predicted?: number;
          away_goals_predicted?: number;
          status?: "pending" | "confirmed" | "scored";
          points?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          phase_id: string;
          status: "pending" | "confirmed";
          confirmed_at: string | null;
          confirmed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          phase_id: string;
          status?: "pending" | "confirmed";
          confirmed_at?: string | null;
          confirmed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          phase_id?: string;
          status?: "pending" | "confirmed";
          confirmed_at?: string | null;
          confirmed_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      confirm_payment: {
        Args: {
          p_payment_id: string;
          p_user_id: string;
          p_phase_id: string;
          p_admin_id: string;
        };
        Returns: undefined;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
