const FLAGS: Record<string, string> = {
  // Americas
  brasil: "🇧🇷",
  brazil: "🇧🇷",
  argentina: "🇦🇷",
  uruguai: "🇺🇾",
  uruguay: "🇺🇾",
  colombia: "🇨🇴",
  chile: "🇨🇱",
  equador: "🇪🇨",
  ecuador: "🇪🇨",
  peru: "🇵🇪",
  venezuela: "🇻🇪",
  paraguai: "🇵🇾",
  paraguay: "🇵🇾",
  bolívia: "🇧🇴",
  bolivia: "🇧🇴",
  mexico: "🇲🇽",
  "costa rica": "🇨🇷",
  panamá: "🇵🇦",
  panama: "🇵🇦",
  honduras: "🇭🇳",
  guatemala: "🇬🇹",
  jamaica: "🇯🇲",
  "el salvador": "🇸🇻",
  canadá: "🇨🇦",
  canada: "🇨🇦",
  eua: "🇺🇸",
  usa: "🇺🇸",
  "estados unidos": "🇺🇸",
  "united states": "🇺🇸",
  cuba: "🇨🇺",
  haiti: "🇭🇹",
  trinidad: "🇹🇹",
  "trinidad e tobago": "🇹🇹",

  // Europe
  alemanha: "🇩🇪",
  germany: "🇩🇪",
  espanha: "🇪🇸",
  spain: "🇪🇸",
  france: "🇫🇷",
  "frança": "🇫🇷",
  england: "🇴🇷",
  ingalterra: "🇴🇷",
  "reino unido": "🇬🇧",
  portugal: "🇵🇹",
  italy: "🇮🇹",
  itália: "🇮🇹",
  netherlands: "🇳🇱",
  holanda: "🇳🇱",
  "países baixos": "🇳🇱",
  belgium: "🇧🇪",
  bélgica: "🇧🇪",
  croatia: "🇭🇷",
  croácia: "🇭🇷",
  denmark: "🇩🇰",
  dinamarca: "🇩🇰",
  switzerland: "🇨🇭",
  suíça: "🇨🇭",
  austria: "🇦🇹",
  áustria: "🇦🇹",
  poland: "🇵🇱",
  polônia: "🇵🇱",
  hungary: "🇭🇺",
  hungria: "🇭🇺",
  serbia: "🇷🇸",
  sérvia: "🇷🇸",
  ukraine: "🇺🇦",
  ucrânia: "🇺🇦",
  sweden: "🇸🇪",
  suécia: "🇸🇪",
  norway: "🇳🇴",
  noruega: "🇳🇴",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  escócia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "república tcheca": "🇨🇿",
  "czech republic": "🇨🇿",
  czechia: "🇨🇿",
  slovakia: "🇸🇰",
  eslováquia: "🇸🇰",
  romania: "🇷🇴",
  romênia: "🇷🇴",
  greece: "🇬🇷",
  grécia: "🇬🇷",
  albania: "🇦🇱",
  albânia: "🇦🇱",
  slovenia: "🇸🇮",
  eslovênia: "🇸🇮",
  turkey: "🇹🇷",
  turquia: "🇹🇷",
  iceland: "🇮🇸",
  islândia: "🇮🇸",

  // Asia / Middle East
  japão: "🇯🇵",
  japan: "🇯🇵",
  "coreia do sul": "🇰🇷",
  "south korea": "🇰🇷",
  china: "🇨🇳",
  irã: "🇮🇷",
  iran: "🇮🇷",
  arábia: "🇸🇦",
  "arábia saudita": "🇸🇦",
  "saudi arabia": "🇸🇦",
  austrália: "🇦🇺",
  australia: "🇦🇺",
  "nova zelândia": "🇳🇿",
  "new zealand": "🇳🇿",
  catar: "🇶🇦",
  qatar: "🇶🇦",
  "emirados árabes": "🇦🇪",
  "united arab emirates": "🇦🇪",
  uae: "🇦🇪",
  iraque: "🇮🇶",
  iraq: "🇮🇶",
  jordânia: "🇯🇴",
  jordan: "🇯🇴",
  uzbekistão: "🇺🇿",
  uzbekistan: "🇺🇿",
  indonesia: "🇮🇩",
  tailândia: "🇹🇭",
  thailand: "🇹🇭",
  "filipinas": "🇵🇭",
  philippines: "🇵🇭",

  // Africa
  marrocos: "🇲🇦",
  morocco: "🇲🇦",
  nigéria: "🇳🇬",
  nigeria: "🇳🇬",
  senegal: "🇸🇳",
  gana: "🇬🇭",
  ghana: "🇬🇭",
  egito: "🇪🇬",
  egypt: "🇪🇬",
  camarões: "🇨🇲",
  cameroon: "🇨🇲",
  mali: "🇲🇱",
  "costa do marfim": "🇨🇮",
  "ivory coast": "🇨🇮",
  tunísia: "🇹🇳",
  tunisia: "🇹🇳",
  argélia: "🇩🇿",
  algeria: "🇩🇿",
  angola: "🇦🇴",
  tanzânia: "🇹🇿",
  tanzania: "🇹🇿",
  "áfrica do sul": "🇿🇦",
  "south africa": "🇿🇦",
  congo: "🇨🇩",
};

export function getFlag(teamName: string): string {
  const key = teamName.toLowerCase().trim();
  return FLAGS[key] ?? "🏳️";
}
